/* sintaxe básica de inserção de dados -> INSERT INTO TABELA...*/
USE PROJETO01;


/*FORMA 01 -> OMITINDO COLUNAS*/
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'A@A.COM', 888888888, '555555555', 'AV.A');
INSERT INTO CLIENTE VALUES('CELIA', 'F', 'B@B.COM', 777777777, '444444444', 'AV.B');
INSERT INTO CLIENTE VALUES('JORGE', 'M', 'C@C.COM', 666666666, '333333333', 'AV.C');


/*FORMA 02 -> DESCREVENDO AS COLUNAS*/
INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LILIAN', 'F', 'AV.D', '222222222', 111111111);


/*FORMA 03 -> INSERT COMPACTO, SOMENTE MYSQL*/
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'A@A.COM', 888888888, '555555555', 'AV.A'),
						  ('CELIA', 'F', 'B@B.COM', 777777777, '444444444', 'AV.B');


/*O comando SELECT
seleção, projeção e junção
*/
SELECT NOW() as DATA_HORA, 'WEBERTY SILVEIRA' as ALUNO;
SELECT 'WEBERTY SILVEIRA';
SELECT 'BANCO DE DADOS';


/*Alias de Colunas*/
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, ENDERECO, SEXO, EMAIL, ENDERECO FROM CLIENTE;


/*APENAS PARA FINS ACADÊMICOS
NÃO USE!!!
*/
SELECT * FROM CLIENTE;


/*FILTRANDO*/
SELECT NOME, ENDERECO FROM CLIENTE 
WHERE SEXO = 'M';


/*LIKE*/
SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%A';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'A%';
