CREATE DATABASE secao07;
USE secao07;

CREATE TABLE FUNCIONARIOS(
	NOME VARCHAR(100),
	SEXO CHAR(1),
	EMAIL VARCHAR(100),
	CPF VARCHAR(1),
	TELEFONE VARCHAR(11),
	ENDERECO VARCHAR(100)
);

INSERT INTO FUNCIONARIOS(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('JOAO','M', 'A@A.COM', '07153542302', '85991561298', 'AV. A, 935');

INSERT INTO FUNCIONARIOS(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('CELIA','F', 'B@B.COM', '07253542302', '86991561298', 'AV. B, 835');

INSERT INTO FUNCIONARIOS(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('JORGE','M', NULL, '07353542302', '87991561298', 'AV. C, 735');

INSERT INTO FUNCIONARIOS(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('LILIAN','F', NULL, '07453542302', '88991561298', 'AV. D, 635');

INSERT INTO FUNCIONARIOS(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('ANA','F', 'C@C.COM', '07553542302', '89991561298', 'AV. E, 535');

INSERT INTO FUNCIONARIOS(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('CARLA','F', 'D@D.COM', '07653542302', '90991561298', 'AV. F, 435');


/*iDENTIFICAR NULOS E NÃO NULOS*/
SELECT NOME, SEXO, EMAIL
FROM FUNCIONARIOS
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, EMAIL
FROM FUNCIONARIOS
WHERE EMAIL IS NOT NULL;

/*ALTERA TODOS OS VALORES*/
UPDATE FUNCIONARIOS
SET EMAIL = 'TESTE@TESTE.COM';

/*IDENTIFICA OS VALORES ANTES DE ALTERAR*/
SELECT * FROM FUNCIONARIOS 
WHERE NOME = 'LILIAN';

/*ALTERANDO*/
UPDATE FUNCIONARIOS
SET EMAIL = 'JOÃO@J.COM'
WHERE NOME = 'JOAO';

UPDATE FUNCIONARIOS
SET EMAIL = 'CELIA@L.COM'
WHERE NOME = 'CELIA';

UPDATE FUNCIONARIOS
SET EMAIL = 'JORGE@L.COM'
WHERE NOME = 'JORGE';

UPDATE FUNCIONARIOS
SET EMAIL = 'LILIAN@L.COM'
WHERE NOME = 'LILIAN';

UPDATE FUNCIONARIOS
SET EMAIL = 'ANA@L.COM'
WHERE NOME = 'ANA';

UPDATE FUNCIONARIOS
SET EMAIL = 'CARLA@L.COM'
WHERE NOME = 'CARLA';

/*DELETANDO TUDO*/
DELETE FROM FUNCIONARIOS;

/*ANTES DE DELETAR CONTE OS REGISTROS PARA SABER SE ESTÁ CERTO*/
SELECT COUNT(*) AS TOTAL FROM FUNCIONARIOS;

SELECT NOME, COUNT(*) FROM FUNCIONARIOS
WHERE NOME = 'ANA';

SELECT NOME FROM FUNCIONARIOS
WHERE NOME = 'ANA';

DELETE FROM FUNCIONARIOS 
WHERE NOME = 'ANA';
