USE SECAO10;

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT NOW() AS TEMPO


SELECT  NOME,
		IFNULL(EMAIL, '*******************') AS 'E-MAIL'
FROM CLIENTE;



SELECT  C.NOME,
		IFNULL(C.EMAIL, '*****************') AS 'EMAIL',
		E.ESTADO,
		T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;


/* VIEW, CRIANDO E DELETANDO*/

CREATE VIEW V_RELATORIO AS
SELECT  C.NOME,
		C.SEXO,
		IFNULL(C.EMAIL, '************') AS 'EMAIL',
		T.TIPO,
		T.NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO
FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE;
	

SELECT * FROM V_RELATORIO;

DROP VIEW V_RELATORIO;

/*CONSULTA COM VIEWS*/
SELECT NOME, E-MAIL
FROM V_RELATORIO;




