USE SECAO14;

SHOW TABLES;


/*VENDEDOR QUE VENDEU MENOS EM MARCO E SEU NOME*/

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);



/*VENDEDOR QUE VENDEU MENOS EM MARCO E SEU NOME*/
SELECT NOME, MARCO 
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);



/*VENDEDOR QUE VENDEU MAIS QUE O VALOR MÉDIO DE FEVEREIRO*/

SELECT NOME, FEVEREIRO 
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

SELECT AVG(FEVEREIRO)
FROM VENDEDORES;