/*CRIANDO AS TABELAS E CONECTANDO COM AS CHAVES*/

CREATE DATABASE PROJETO02;
USE PROJETO02;

CREATE TABLE CLIENTES(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONES(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TELEFONE VARCHAR(30),
	
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE CARROS(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE MARCAS(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(15),
	
	ID_CARRO INT,
	FOREIGN KEY(ID_CARRO)
	REFERENCES CARROS(IDCARRO)
);

CREATE TABLE CORES(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(15),
	
	ID_CARRO INT,
	FOREIGN KEY(ID_CARRO)
	REFERENCES CARROS(IDCARRO)
);






/*INSERINDO VALORES DE TESTE*/

INSERT INTO CLIENTES VALUES(NULL, 'JOÃO');
INSERT INTO TELEFONES VALUES(NULL, '85 9 91561298', 1);
INSERT INTO CARROS VALUES(NULL, 'CELTA', 1);
INSERT INTO MARCAS VALUES(NULL, 'RENAULT', 1);
INSERT INTO CORES VALUES(NULL, 'PRETO', 1);

INSERT INTO CLIENTES VALUES(NULL, 'PEDRO');
INSERT INTO TELEFONES VALUES(NULL, '85 9 85858585', 2);
INSERT INTO CARROS VALUES(NULL, 'WIND', 2);
INSERT INTO MARCAS VALUES(NULL, 'CHEVROLET', 1);
INSERT INTO CORES VALUES(NULL, 'BRANCO', 2);

INSERT INTO TELEFONES VALUES(NULL, '85 9 84848484', 2);
INSERT INTO CORES VALUES(NULL, 'CINZA', 2);




/*CONSULTANDO OS VALORES CADASTRADOS COM PROCEDURE*/

DELIMITER $

CREATE PROCEDURE RELATORIO2()

BEGIN

	SELECT A.IDCLIENTE, A.NOME, B.MODELO, C.TELEFONE, D.COR, E.MARCA
	FROM CLIENTES A
		INNER JOIN CARROS B
		ON A.IDCLIENTE = B.ID_CLIENTE
		
		INNER JOIN TELEFONES C
		ON A.IDCLIENTE = C.ID_CLIENTE
		
		INNER JOIN CORES D
		ON B.IDCARRO = D.ID_CARRO;
		
		INNER JOIN MARCAS E
		ON B.IDCARRO = E.ID_CARRO;

END

$
DELIMITER ;



CALL RELATORIO2();